name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
- group: terraform_variables

trigger:
- master

pr:
- develop
- master 

resources:
  containers:
    - container: terraform
      image: kuhlmanlabs.azurecr.io/build/terraform:latest
      endpoint: kuhlman-labs-container-registry

stages:
      
- stage: Terraform_Validate
  displayName: Check Terraform for format and validation
  jobs:
  - job: Format_Terraform
    pool:
      vmImage: 'ubuntu-16.04'
    container: terraform  
    steps:
      - script: terraform fmt -check -list=true 
  - job: Validate_Terraform
    pool:
      vmImage: 'ubuntu-16.04'
    container: terraform    
    steps:  
    - task: Bash@3  
      inputs:
        filePath: './scripts/bash/pipeline/validate_terraform.sh'  

- stage: Terraform_Apply
  displayName: Run Terraform apply for solutions 
  jobs:
  - job: Apply_Terraform
    pool:
      vmImage: 'ubuntu-16.04'
    container: terraform   
    steps:  
    - task: Bash@3  
      inputs:
        filePath: './scripts/bash/pipeline/plan-apply.sh'
  dependsOn: Terraform_Validate

- stage: Terraform_Destroy
  displayName: Run Terraform Destroy for solutions 
  jobs:
  - job: Destroy_Terraform
    pool:
      vmImage: 'ubuntu-16.04'
    container: terraform   
    steps:  
    - task: Bash@3  
      inputs:
        filePath: './scripts/bash/pipeline/destroy.sh'
  dependsOn: Terraform_Apply   
      