name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
- group: terraform_variables

trigger:
- develop

pr:
- develop
- master 

resources:
  containers:
    - container: terraform
      image: brettkuhlman/terraform:latest

stages:
      
#- stage: Terraform_Fmt
#  displayName: Check Terraform Format
#  jobs:
#  - job: Format_Terraform
#    pool:
#      vmImage: 'ubuntu-16.04'
#    container: terraform  
#    steps:
#      - script: terraform fmt -recursive -check -list=true

- stage: Terraform_Validate
  displayName: Validate Terraform Syntax 
  jobs:      
  - job: Validate_Terraform
    pool:
      vmImage: 'ubuntu-16.04'
    container: terraform    
    steps:  
    - task: Bash@3  
      inputs:
        filePath: './scripts/pipeline/validate_terraform.sh'
  #dependsOn: Terraform_Fmt        

- stage: Terraform_Apply
  displayName: Run Terraform apply for solutions 
  jobs:
  - job: Apply_Terraform
    pool:
      vmImage: 'ubuntu-16.04'
    container: terraform   
    steps:  
    - task: Bash@3  
      inputs:
        filePath: './scripts/pipeline/plan-apply.sh'
  dependsOn: Terraform_Validate

- stage: Terraform_Destroy
  displayName: Run Terraform destroy for solutions 
  jobs:
  - job: Destroy_Terraform
    pool:
      vmImage: 'ubuntu-16.04'
    container: terraform   
    steps:  
    - task: Bash@3  
      inputs:
        filePath: './scripts/pipeline/destroy.sh'
  dependsOn: Terraform_Apply   
      